#! /bin/sh
# chkconfig: 2345 85 15
# Description: Startup script for webconsole webserver on Debian. Place in /etc/init.d and
# run 'update-rc.d -f webconsole defaults', or use the appropriate command on your
# distro. For CentOS/Redhat run: 'chkconfig --add webconsole'

### BEGIN INIT INFO
# Provides:         webconsole
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the webconsole web server
# Description:       starts webconsole using start-stop-daemon
### END INIT INFO

# Author:   licess
# website:  https://webconsole.realclouds.org

NAME=webconsole

PIDFILE=/opt/webconsole/log/apibox.pid 
. /etc/init.d/functions
webconsole_start() {
	nohup  /opt/webconsole/bin/apibox   start   >/dev/null   2>&1 &
}

webconsole_stop() {
        /opt/webconsole/bin/apibox  stop   >/dev/null   2>&1 &
        rm -rf  $PIDFILE

}

case "$1" in
    start)

        if [ -f "$PIDFILE" ]; then
            echo "$NAME (pid `pidof $NAME`) already running..."
            exit 1
        fi
        webconsole_start
        echo "$NAME (pid `pidof $NAME`) is running..."
        ;;

    stop)
        echo -n "Stoping $NAME... "
        webconsole_stop
         echo "$NAME   is  stopped..."
        exit 1
        ;;

    status)
        if [ -f "$PIDFILE" ]; then
            echo "$NAME (pid `pidof $NAME`) is running..."
        else
            echo "$NAME is stopped."
            exit 0
        fi
           ;;
    restart)
        webconsole_stop
             echo -n "Stoping $NAME... "
             echo "$NAME   is  stopped..."
        sleep 1
        webconsole_start
            echo "$NAME (pid `pidof $NAME`) is running..."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1

esac
exit 0
